### ISSUE TITLE
00_setup.md should mention that this repo should be cloned recursively

### ISSUE THREAD

**Issue by cboulay** [brandbci/brand-tutorial#1]
I had cloned all the repos separately and I was running `supervisor` from a standalone `brand` clone. I was a bit confused when 01_calibration.ipynb didn't have any streams other than the meta streams; I didn't realize there was an expected hierarchy so `make` in the `brand` folder would also call make in the `brand-modules` subfolders.

I think that 00_setup.md should mention in the Installation checklist that it is expected that this brand-tutorial repository should have been cloned recursively or that the user can now run `git submodule init && git submodule update`.

**Comment by yahiaali** [comment]
Thanks @cboulay. I've now added a note to the installation checklist that shows the commands for cloning with submodules (commit https://github.com/brandbci/brand-tutorial/commit/be05170e4e42b9829072d2ba72fa8464ea7669f9).
